name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude-code-action:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
    env:
      CLAUDE_OAUTH_TOKEN: ""
      CLAUDE_API_KEY: ""
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set Claude authentication variables
        id: claude_auth
        run: |
          if [ -n "${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}" ]; then
            echo "CLAUDE_OAUTH_TOKEN=${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}" >> $GITHUB_ENV
            echo "CLAUDE_API_KEY=" >> $GITHUB_ENV
            echo "auth_method=oauth" >> $GITHUB_OUTPUT
            echo "Using OAuth token for authentication"
          elif [ -n "${{ secrets.ANTHROPIC_API_KEY }}" ]; then
            echo "CLAUDE_OAUTH_TOKEN=" >> $GITHUB_ENV
            echo "CLAUDE_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" >> $GITHUB_ENV
            echo "auth_method=api_key" >> $GITHUB_OUTPUT
            echo "Using API key for authentication"
          else
            echo "CLAUDE_OAUTH_TOKEN=" >> $GITHUB_ENV
            echo "CLAUDE_API_KEY=" >> $GITHUB_ENV
            echo "auth_method=none" >> $GITHUB_OUTPUT
            echo "::error::No Claude authentication available. Please configure either CLAUDE_CODE_OAUTH_TOKEN or ANTHROPIC_API_KEY secrets."
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: 'maven'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6

      - name: Install UV and Trivy for MCP server
        run: |
          # Install UV for Python MCP server
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
          # Install Trivy for vulnerability scanning
          sudo apt-get update
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy

      - name: Run Claude PR Action
        if: steps.claude_auth.outputs.auth_method != 'none'
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ env.CLAUDE_OAUTH_TOKEN }}
          anthropic_api_key: ${{ env.CLAUDE_API_KEY }}
          timeout_minutes: "60"
          allowed_tools: "Bash,Task,mcp__mvn-mcp-server__check_version_tool,mcp__mvn-mcp-server__check_version_batch_tool,mcp__mvn-mcp-server__list_available_versions_tool,mcp__mvn-mcp-server__scan_java_project_tool,mcp__mvn-mcp-server__analyze_pom_file_tool"
          mcp_config: |
            {
              "mcpServers": {
                "mvn-mcp-server": {
                  "type": "stdio",
                  "command": "uvx",
                  "args": [
                    "--from",
                    "git+https://github.com/danielscholl-osdu/mvn-mcp-server@main",
                    "mvn-mcp-server"
                  ],
                  "env": {},
                  "tools": ["*"]
                }
              }
            }