name: Deploy Documentation

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths:
      - 'doc/src/**'
      - 'doc/mkdocs.yml'
      - '.github/workflows/docs.yml'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  check_template:
    name: Check if template repository
    runs-on: ubuntu-latest
    outputs:
      is_template: ${{ steps.check.outputs.is_template }}
    steps:
      - name: Check repository type
        id: check
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "IS_TEMPLATE variable: ${{ vars.IS_TEMPLATE }}"
          echo "Template flag: ${{ github.event.repository.is_template }}"
          
          # Check if IS_TEMPLATE variable is set to true (template development repo protection)
          if [[ "${{ vars.IS_TEMPLATE }}" == "true" ]]; then
            echo "✅ IS_TEMPLATE variable is true - this is the template repository"
            echo "is_template=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # Check if this is the original template repository by name
          if [[ "${{ github.repository }}" == "danielscholl-osdu/osdu-fork-template" ]]; then
            echo "✅ Repository name matches template - this is the template repository"
            echo "is_template=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # Check GitHub's template flag
          if [[ "${{ github.event.repository.is_template }}" == "true" ]]; then
            echo "✅ GitHub template flag is true - this is the template repository"
            echo "is_template=true" >> $GITHUB_OUTPUT
          else
            echo "❌ This appears to be a fork instance - documentation deployment should not run"
            echo "is_template=false" >> $GITHUB_OUTPUT
          fi

  # Documentation deployment
  deploy:
    name: Deploy documentation to GitHub Pages
    needs: check_template
    # Only deploy documentation in the template repository
    if: |
      needs.check_template.outputs.is_template == 'true' &&
      ((github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch')
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs mkdocs-material mkdocs-minify-plugin pymdown-extensions
      - run: |
          cd doc
          mkdocs gh-deploy --force --clean --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}